# Generated by Django 5.2.4 on 2025-11-08 22:17

from django.db import migrations, models

def link_narratives_to_statements(apps, schema_editor):
    """
    Populate the new 'targeted_statements' field by finding the corresponding
    Statement for each old DocumentNode link.
    """
    TrameNarrative = apps.get_model('argument_manager', 'TrameNarrative')
    LibraryNode = apps.get_model('document_manager', 'LibraryNode')

    for narrative in TrameNarrative.objects.all():
        # Find all the old DocumentNodes this narrative was linked to.
        old_nodes = narrative.allegations_ciblees.all()
        
        # Find the corresponding new LibraryNodes by matching the 'item' and 'text'.
        # This is a reliable way to find the migrated nodes.
        # We then get the associated Statement from that LibraryNode.
        statements_to_link = []
        for old_node in old_nodes:
            try:
                # Find the LibraryNode that corresponds to the old DocumentNode
                # We match on 'item' and the Statement's 'text'
                corresponding_library_node = LibraryNode.objects.get(
                    item=old_node.item,
                    statement__text=old_node.text
                )
                statements_to_link.append(corresponding_library_node.statement)
            except LibraryNode.DoesNotExist:
                # Handle cases where a corresponding node might not be found
                print(f"Warning: Could not find a matching LibraryNode for old DocumentNode ID {old_node.id}")
            except LibraryNode.MultipleObjectsReturned:
                # Handle cases where the match is not unique
                print(f"Warning: Found multiple matching LibraryNodes for old DocumentNode ID {old_node.id}")

        # Add the found statements to the new ManyToManyField
        if statements_to_link:
            narrative.targeted_statements.set(statements_to_link)


class Migration(migrations.Migration):

    dependencies = [
        ('argument_manager', '0001_initial'),
        ('document_manager', '0002_statement_document_librarynode'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramenarrative',
            name='targeted_statements',
            field=models.ManyToManyField(blank=True, help_text='The specific statements targeted by this narrative (New Architecture).', related_name='narratives', to='document_manager.statement'),
        ),
        migrations.AlterField(
            model_name='tramenarrative',
            name='allegations_ciblees',
            field=models.ManyToManyField(blank=True, help_text='Les allégations spécifiques ciblées par cet argumentaire.', related_name='trames_narratives', to='document_manager.documentnode'),
        ),
        migrations.RunPython(link_narratives_to_statements, migrations.RunPython.noop),
    ]
