# Generated by Django 5.2.4 on 2025-11-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argument_manager', '0002_tramenarrative_targeted_statements_and_more'),
        ('document_manager', '0002_statement_document_librarynode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramenarrative',
            name='allegations_ciblees',
        ),
        migrations.AlterField(
            model_name='tramenarrative',
            name='targeted_statements',
            field=models.ManyToManyField(blank=True, help_text='The specific statements targeted by this narrative.', related_name='narratives', to='document_manager.statement'),
        ),
    ]
