# Generated by Django 5.2.4 on 2025-11-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argument_manager', '0003_remove_tramenarrative_allegations_ciblees_and_more'),
        ('document_manager', '0007_statement_is_user_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramenarrative',
            name='source_statements',
            field=models.ManyToManyField(blank=True, help_text='Statements from other documents used as evidence.', related_name='narratives_using_this_statement_as_evidence', to='document_manager.statement'),
        ),
        migrations.AlterField(
            model_name='tramenarrative',
            name='targeted_statements',
            field=models.ManyToManyField(blank=True, help_text='The specific statements targeted by this narrative.', related_name='narratives_targeting_this_statement', to='document_manager.statement'),
        ),
    ]
