# Generated by Django 5.2.4 on 2025-11-26 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('argument_manager', '0004_tramenarrative_source_statements_and_more'),
        ('document_manager', '0007_statement_is_user_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerjuryArgument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., 'Allégation N°1 : Fausse déclaration sur...'", max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('text_declaration', models.TextField(help_text='Describe the context of the lie (Action/Reference).', verbose_name='1. Déclaration faite sous serment')),
                ('text_proof', models.TextField(help_text='Insert evidence here using the custom plugin.', verbose_name='2. Preuve de la fausseté')),
                ('text_mens_rea', models.TextField(help_text='Why did they know it was false?', verbose_name='3. Connaissance de la fausseté (Mens Rea)')),
                ('text_intent', models.TextField(help_text='What did they hope to gain?', verbose_name='4. Intention de tromper le tribunal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('targeted_statements', models.ManyToManyField(help_text='The specific false allegations being refuted in this block.', related_name='refutations', to='document_manager.statement')),
                ('trame_narrative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arguments', to='argument_manager.tramenarrative')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
# Generated by Django 5.2.4 on 2025-11-26 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('argument_manager', '0004_tramenarrative_source_statements_and_more'),
        ('document_manager', '0007_statement_is_user_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerjuryArgument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., 'Allégation N°1 : Fausse déclaration sur...'", max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('text_declaration', models.TextField(help_text='Describe the context of the lie (Action/Reference).', verbose_name='1. Déclaration faite sous serment')),
                ('text_proof', models.TextField(help_text='Insert evidence here using the custom plugin.', verbose_name='2. Preuve de la fausseté')),
                ('text_mens_rea', models.TextField(help_text='Why did they know it was false?', verbose_name='3. Connaissance de la fausseté (Mens Rea)')),
                ('text_intent', models.TextField(help_text='What did they hope to gain?', verbose_name='4. Intention de tromper le tribunal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('targeted_statements', models.ManyToManyField(help_text='The specific false allegations being refuted in this block.', related_name='refutations', to='document_manager.statement')),
                ('trame_narrative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arguments', to='argument_manager.tramenarrative')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
