# Generated by Django 5.2.4 on 2025-11-25 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argument_manager', '0005_perjuryargument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perjuryargument',
            options={},
        ),
        migrations.RemoveField(
            model_name='perjuryargument',
            name='order',
        ),
        migrations.RemoveField(
            model_name='perjuryargument',
            name='targeted_statements',
        ),
        migrations.RemoveField(
            model_name='perjuryargument',
            name='text_intent',
        ),
        migrations.RemoveField(
            model_name='perjuryargument',
            name='title',
        ),
        migrations.RemoveField(
            model_name='perjuryargument',
            name='trame_narrative',
        ),
        migrations.AddField(
            model_name='perjuryargument',
            name='text_legal_consequence',
            field=models.TextField(blank=True, help_text='What did they hope to gain?', verbose_name='4. Intention de tromper le tribunal'),
        ),
        migrations.AddField(
            model_name='perjuryargument',
            name='trame',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perjury_argument', to='argument_manager.tramenarrative'),
        ),
        migrations.AlterField(
            model_name='perjuryargument',
            name='text_declaration',
            field=models.TextField(blank=True, help_text='Contextualise the lie. (Use the plugin to link the Targeted Statement here)', verbose_name='1. Déclaration faite sous serment'),
        ),
        migrations.AlterField(
            model_name='perjuryargument',
            name='text_mens_rea',
            field=models.TextField(blank=True, help_text='Demonstrate that they KNEW it was false.', verbose_name='3. Connaissance de la fausseté (Mens Rea)'),
        ),
        migrations.AlterField(
            model_name='perjuryargument',
            name='text_proof',
            field=models.TextField(blank=True, help_text='Demonstrate why it is false. (Use the plugin to inject Events, Emails, and Source Statements here)', verbose_name='2. Preuve de la fausseté'),
        ),
    ]
