# Generated by Django 5.2.4 on 2025-12-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argument_manager', '0006_alter_perjuryargument_options_and_more'),
        ('googlechat_manager', '0002_chatsequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramenarrative',
            name='citations_chat',
            field=models.ManyToManyField(blank=True, help_text='Sequences of chat messages used as evidence.', related_name='trames_narratives', to='googlechat_manager.chatsequence'),
        ),
    ]
