# Generated by Django 5.2.4 on 2025-12-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argument_manager', '0007_tramenarrative_citations_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramenarrative',
            name='ai_analysis_json',
            field=models.JSONField(blank=True, default=dict, help_text="Analyse objective générée par l'IA confrontant preuves vs allégations."),
        ),
        migrations.AddField(
            model_name='tramenarrative',
            name='analysis_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perjuryargument',
            name='text_declaration',
            field=models.TextField(blank=True, help_text='Contextualise the lie.', verbose_name='1. Déclaration faite sous serment'),
        ),
        migrations.AlterField(
            model_name='perjuryargument',
            name='text_proof',
            field=models.TextField(blank=True, help_text='Demonstrate why it is false.', verbose_name='2. Preuve de la fausseté'),
        ),
    ]
