# Generated by Django 5.2.4 on 2025-11-07 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document_manager', '0001_initial'),
        ('email_manager', '0001_initial'),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The date of the event.')),
                ('explanation', models.TextField(blank=True, help_text='A detailed explanation of the event, auto-filled for photo clusters.')),
                ('email_quote', models.TextField(blank=True, help_text='A specific quote or excerpt from an email.', null=True)),
                ('allegation', models.ForeignKey(blank=True, help_text='The specific allegation this event supports or refutes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='document_manager.documentnode')),
                ('linked_email', models.ForeignKey(blank=True, help_text='The specific email this quote is from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='email_manager.email')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'SupportingEvidence_supportingevidence',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='SupportingEvidenceLinkedPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supportingevidence', models.ForeignKey(db_column='supportingevidence_id', on_delete=django.db.models.deletion.DO_NOTHING, to='events.event')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='photos.photo')),
            ],
            options={
                'db_table': 'SupportingEvidence_supportingevidence_linked_photos',
                'unique_together': {('supportingevidence', 'photo')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='linked_photos',
            field=models.ManyToManyField(blank=True, help_text='A collection of photos related to this event.', related_name='events', through='events.SupportingEvidenceLinkedPhotos', to='photos.photo'),
        ),
        migrations.AddField(
            model_name='event',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='The parent event for this piece of evidence.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='events.event'),
        ),
    ]
