# Generated by Django 5.2.4 on 2025-11-08 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='allegation',
        ),
    ]
