# Generated by Django 5.2.4 on 2026-03-30 12:29

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_allegation'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
