# Generated by Django 5.2.4 on 2025-11-25 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('argument_manager', '0006_alter_perjuryargument_options_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('document_manager', '0007_statement_is_user_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerjuryContestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('final_sec1_declaration', models.TextField(blank=True, verbose_name='1. Déclaration')),
                ('final_sec2_proof', models.TextField(blank=True, verbose_name='2. Preuve')),
                ('final_sec3_mens_rea', models.TextField(blank=True, verbose_name='3. Mens Rea')),
                ('final_sec4_intent', models.TextField(blank=True, verbose_name='4. Intention')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contestations', to='case_manager.legalcase')),
                ('supporting_narratives', models.ManyToManyField(related_name='supported_contestations', to='argument_manager.tramenarrative')),
                ('targeted_statements', models.ManyToManyField(related_name='contestations', to='document_manager.statement')),
            ],
        ),
        migrations.CreateModel(
            name='AISuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_version', models.CharField(default='gemini-pro', max_length=50)),
                ('suggestion_sec1', models.TextField(blank=True)),
                ('suggestion_sec2', models.TextField(blank=True)),
                ('suggestion_sec3', models.TextField(blank=True)),
                ('suggestion_sec4', models.TextField(blank=True)),
                ('contestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to='case_manager.perjurycontestation')),
            ],
        ),
        migrations.CreateModel(
            name='ExhibitRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('exhibit_number', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibits', to='case_manager.legalcase')),
            ],
            options={
                'ordering': ['exhibit_number'],
                'unique_together': {('case', 'content_type', 'object_id')},
            },
        ),
    ]
