# Generated by Django 5.2.4 on 2025-11-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aisuggestion',
            name='suggestion_sec1',
        ),
        migrations.RemoveField(
            model_name='aisuggestion',
            name='suggestion_sec2',
        ),
        migrations.RemoveField(
            model_name='aisuggestion',
            name='suggestion_sec3',
        ),
        migrations.RemoveField(
            model_name='aisuggestion',
            name='suggestion_sec4',
        ),
        migrations.AddField(
            model_name='aisuggestion',
            name='content',
            field=models.JSONField(default=dict),
        ),
    ]
