# Generated by Django 5.2.4 on 2025-11-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0002_remove_aisuggestion_suggestion_sec1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisuggestion',
            name='parsing_success',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aisuggestion',
            name='raw_response',
            field=models.TextField(blank=True, help_text="Réponse brute de l'IA avant traitement JSON", null=True),
        ),
    ]
