# Generated by Django 5.2.4 on 2025-12-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0003_aisuggestion_parsing_success_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perjurycontestation',
            name='police_complaint_data',
            field=models.JSONField(blank=True, default=dict, help_text='Contenu structuré de la plainte (Objet, Corpus Delicti, Mens Rea...)', verbose_name='Données Plainte Policière'),
        ),
    ]
