# Generated by Django 5.2.4 on 2025-12-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0004_perjurycontestation_police_complaint_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perjurycontestation',
            name='police_complaint_data',
        ),
        migrations.AddField(
            model_name='perjurycontestation',
            name='police_report_data',
            field=models.JSONField(blank=True, default=dict, help_text='Contenu structuré de la plainte criminelle (Art 131).'),
        ),
        migrations.AddField(
            model_name='perjurycontestation',
            name='police_report_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
