# Generated by Django 5.2.4 on 2025-12-05 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0005_remove_perjurycontestation_police_complaint_data_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProducedExhibit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(db_index=True, help_text='Integer for strict sorting (1, 2, 3...)')),
                ('label', models.CharField(help_text="The display label (e.g., 'P-1', 'P-1-1')", max_length=20)),
                ('date_display', models.CharField(blank=True, help_text='The string to show in the Date column', max_length=255)),
                ('description', models.TextField(help_text='The calculated description (Subject, Explanation, or Quote)')),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produced_exhibits', to='case_manager.legalcase')),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Produced Exhibit',
                'ordering': ['sort_order'],
            },
        ),
    ]
