# Generated by Django 5.2.4 on 2025-12-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0006_producedexhibit'),
    ]

    operations = [
        migrations.AddField(
            model_name='producedexhibit',
            name='exhibit_type',
            field=models.CharField(blank=True, help_text="The user-friendly type of the exhibit (e.g., 'Courriel', 'Photo')", max_length=100),
        ),
        migrations.AddField(
            model_name='producedexhibit',
            name='parties',
            field=models.CharField(blank=True, help_text='Calculated author/recipient information.', max_length=500),
        ),
    ]
