# Generated by Django 5.2.4 on 2025-12-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0007_producedexhibit_exhibit_type_producedexhibit_parties'),
    ]

    operations = [
        migrations.AddField(
            model_name='producedexhibit',
            name='public_url',
            field=models.CharField(blank=True, help_text='URL to the public view of the source document.', max_length=500, null=True),
        ),
    ]
