import json

def clean_dump(input_file, output_file):
    print(f"Reading {input_file}...")
    with open(input_file, 'r') as f:
        data = json.load(f)

    cleaned_data = []
    removed_counts = {
        'auth.permission': 0,
        'contenttypes.contenttype': 0,
        'admin.logentry': 0, # Often causes issues if users don't exist yet
        'sessions.session': 0, # Usually not needed
    }

    for entry in data:
        model = entry.get('model')
        
        # Remove system models that are auto-generated by migrate
        if model in removed_counts:
            removed_counts[model] += 1
            continue
            
        # Fix ProducedExhibit field
        if model == 'case_manager.producedexhibit':
            if 'fields' in entry and 'public_url' in entry['fields']:
                del entry['fields']['public_url']
        
        cleaned_data.append(entry)

    print("Removed entries:")
    for model, count in removed_counts.items():
        print(f"  {model}: {count}")

    print(f"Writing {len(cleaned_data)} entries to {output_file}...")
    with open(output_file, 'w') as f:
        json.dump(cleaned_data, f, indent=2)

if __name__ == "__main__":
    clean_dump('db_dump_with_users.json', 'db_dump_cleaned_final.json')
