# Generated by Django 5.2.4 on 2025-11-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('node_type', models.CharField(choices=[('library', 'Bibliothèque'), ('document', 'Document Principal'), ('section', 'Section'), ('paragraph', 'Paragraphe / Contenu'), ('root', 'Nœud Racine Générique')], default='paragraph', help_text='Le type de ce nœud (ex: bibliothèque, document, section).', max_length=20)),
                ('item', models.CharField(help_text="Nom court ou titre du nœud (ex: 'requete', 'chapitre').", max_length=555)),
                ('text', models.TextField(blank=True, help_text='Le contenu textuel de ce nœud de document.', null=True)),
                ('is_true', models.BooleanField(default=True, help_text="Indique si l'affirmation est considérée comme vraie.")),
                ('is_falsifiable', models.BooleanField(blank=True, default=None, help_text="Indique si une affirmation (qui est fausse) est falsifiable. Non applicable si l'affirmation est vraie.", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nœud de Document',
                'verbose_name_plural': 'Nœuds de Documents',
                'abstract': False,
            },
        ),
    ]
