# Generated by Django 5.2.4 on 2025-11-08 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def migrate_children(old_parent, new_parent, document, Statement, LibraryNode, DocumentNode):
    """
    A recursive function to migrate children from the old tree to the new tree.
    This version uses manual queries instead of treebeard methods.
    """
    # Manually query for children instead of using old_parent.get_children()
    old_children = list(DocumentNode.objects.filter(
        path__startswith=old_parent.path,
        depth=old_parent.depth + 1
    ).order_by('path'))

    if not old_children:
        return

    for old_child_node in old_children:
        # Create the Statement for the child node.
        child_statement = Statement.objects.create(
            text=old_child_node.text,
            is_true=old_child_node.is_true,
            is_falsifiable=old_child_node.is_falsifiable,
            created_at=old_child_node.created_at,
            updated_at=old_child_node.updated_at,
        )

        # Manually calculate path and depth for the new child.
        new_parent.numchild += 1
        new_child_path = f"{new_parent.path}{new_parent.numchild:04x}"
        new_child_depth = new_parent.depth + 1

        # Create the new LibraryNode object.
        new_child_node = LibraryNode.objects.create(
            document=document,
            statement=child_statement,
            item=old_child_node.item,
            path=new_child_path,
            depth=new_child_depth,
            numchild=0,
            created_at=old_child_node.created_at,
            updated_at=old_child_node.updated_at,
        )

        # Recurse to migrate the grandchildren.
        migrate_children(old_child_node, new_child_node, document, Statement, LibraryNode, DocumentNode)

    # After the loop, save the final child count for the parent.
    new_parent.save(update_fields=['numchild'])


def migrate_data(apps, schema_editor):
    """
    Main data migration function.
    It finds old documents, creates new ones, and migrates the tree structure.
    """
    DocumentNode = apps.get_model('document_manager', 'DocumentNode')
    Document = apps.get_model('document_manager', 'Document')
    Statement = apps.get_model('document_manager', 'Statement')
    LibraryNode = apps.get_model('document_manager', 'LibraryNode')

    document_root_nodes = DocumentNode.objects.filter(depth=2).order_by('path')
    
    last_root_path_int = 0

    for old_doc_root_node in document_root_nodes:
        # 1. Create the new Document object.
        new_document = Document.objects.create(
            title=old_doc_root_node.item,
            created_at=old_doc_root_node.created_at,
            updated_at=old_doc_root_node.updated_at,
        )

        # 2. Create the Statement for the root node itself.
        root_statement = Statement.objects.create(
            text=old_doc_root_node.text,
            is_true=old_doc_root_node.is_true,
            is_falsifiable=old_doc_root_node.is_falsifiable,
            created_at=old_doc_root_node.created_at,
            updated_at=old_doc_root_node.updated_at,
        )

        # 3. Manually create the root node for the new tree.
        last_root_path_int += 1
        new_root_path = f"{last_root_path_int:04x}"

        new_root_node = LibraryNode.objects.create(
            document=new_document,
            statement=root_statement,
            item=old_doc_root_node.item,
            path=new_root_path,
            depth=1,
            numchild=0,
            created_at=old_doc_root_node.created_at,
            updated_at=old_doc_root_node.updated_at,
        )

        # 4. Recursively migrate all children.
        migrate_children(old_doc_root_node, new_root_node, new_document, Statement, LibraryNode, DocumentNode)


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('is_true', models.BooleanField(default=True)),
                ('is_falsifiable', models.BooleanField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Statement',
                'verbose_name_plural': 'Statements (New)',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The official title of the document.', max_length=555)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents (New)',
            },
        ),
        migrations.CreateModel(
            name='LibraryNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('item', models.CharField(help_text='Short name or title for this node in the tree.', max_length=555)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(help_text='The document this node belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='document_manager.document')),
                ('statement', models.ForeignKey(blank=True, help_text='The content this node represents.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes', to='document_manager.statement')),
            ],
            options={
                'verbose_name': 'Library Node',
                'verbose_name_plural': 'Library Nodes (New)',
            },
        ),
        migrations.RunPython(migrate_data, migrations.RunPython.noop),
    ]
