# Generated by Django 5.2.4 on 2025-11-08 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('argument_manager', '0003_remove_tramenarrative_allegations_ciblees_and_more'),
        ('document_manager', '0002_statement_document_librarynode'),
        ('events', '0002_remove_event_allegation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentNode',
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterModelOptions(
            name='librarynode',
            options={'verbose_name': 'Library Node', 'verbose_name_plural': 'Library Nodes'},
        ),
        migrations.AlterModelOptions(
            name='statement',
            options={'verbose_name': 'Statement', 'verbose_name_plural': 'Statements'},
        ),
    ]
