# Generated by Django 5.2.4 on 2025-11-10 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('document_manager', '0003_delete_documentnode_alter_document_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='source_type',
            field=models.CharField(choices=[('REPRODUCED', 'Reproduced (from external file)'), ('PRODUCED', 'Produced (created manually)')], default='REPRODUCED', help_text='Indicates if the document was imported or created manually.', max_length=20),
        ),
        migrations.AddField(
            model_name='librarynode',
            name='content_type',
            field=models.ForeignKey(help_text='The model class that this node points to (e.g., Statement or TrameNarrative).', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='librarynode',
            name='object_id',
            field=models.PositiveIntegerField(help_text='The primary key of the object this node points to.', null=True),
        ),
    ]
