# Generated by Django 5.2.4 on 2025-11-10 15:01

from django.db import migrations

def migrate_statements_to_gfk(apps, schema_editor):
    """
    Copies the relationship from the old 'statement' foreign key
    to the new generic foreign key fields (content_type, object_id).
    """
    LibraryNode = apps.get_model('document_manager', 'LibraryNode')
    Statement = apps.get_model('document_manager', 'Statement')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    # Get the ContentType for the Statement model
    statement_content_type = ContentType.objects.get_for_model(Statement)

    # Find all nodes that have a statement linked but don't have the GFK set yet
    nodes_to_migrate = LibraryNode.objects.filter(
        statement__isnull=False,
        content_type__isnull=True
    )

    for node in nodes_to_migrate:
        node.content_type = statement_content_type
        node.object_id = node.statement_id
    
    # Update all the modified nodes in a single, efficient bulk operation
    if nodes_to_migrate:
        LibraryNode.objects.bulk_update(nodes_to_migrate, ['content_type', 'object_id'])

def reverse_migration(apps, schema_editor):
    """
    Reverses the migration by nulling out the GFK fields for nodes
    that point to a Statement. This is a non-destructive reverse operation.
    """
    LibraryNode = apps.get_model('document_manager', 'LibraryNode')
    Statement = apps.get_model('document_manager', 'Statement')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    statement_content_type = ContentType.objects.get_for_model(Statement)

    nodes_to_reverse = LibraryNode.objects.filter(content_type=statement_content_type)

    for node in nodes_to_reverse:
        node.content_type = None
        node.object_id = None

    if nodes_to_reverse:
        LibraryNode.objects.bulk_update(nodes_to_reverse, ['content_type', 'object_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0004_document_source_type_librarynode_content_type_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_statements_to_gfk, reverse_code=reverse_migration),
    ]
