# Generated by Django 5.2.4 on 2025-11-10 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0005_migrate_statements_to_gfk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarynode',
            name='statement',
        ),
    ]
