# Generated by Django 5.2.4 on 2025-11-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0006_remove_librarynode_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='is_user_created',
            field=models.BooleanField(default=False, help_text='True if this statement was created by a user through the editor, False if imported.'),
        ),
    ]
