# Generated by Django 5.2.4 on 2025-11-27 18:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0008_alter_document_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_original_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
