# Generated by Django 5.2.4 on 2025-11-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0009_document_document_original_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='solemn_declaration',
            field=models.TextField(blank=True, help_text='The solemn declaration text for this document.'),
        ),
    ]
