# Generated by Django 5.2.4 on 2026-01-21 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0010_document_solemn_declaration'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_source',
            field=models.FileField(blank=True, help_text='The original source file (PDF) if this is a REPRODUCED document.', null=True, upload_to='evidence_files/'),
        ),
    ]
