# Generated by Django 5.2.4 on 2026-03-29 21:39

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0011_document_file_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
