# Generated by Django 5.2.4 on 2026-01-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protagonist_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='protagonist',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text="Link to the protagonist's LinkedIn profile.", null=True),
        ),
    ]
