from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType


class GeminiResponse(models.Model):
    """
    Stores a response generated by an AI model. This response can be
    linked to any other model instance in the project (e.g., a PhotoDocument,
    a PDFDocument, an EmailThread, etc.).
    """
    # Fields to link to ANY other model
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    prompt = models.TextField(
        help_text="The text prompt sent to the AI API."
    )
    response = models.TextField(
        help_text="The text response received from the AI API."
    )
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"AI Response for {self.content_object}"

    class Meta:
        ordering = ['-created_at']
        verbose_name = "AI Service Response"
        verbose_name_plural = "AI Service Responses"
        indexes = [
            models.Index(fields=["content_type", "object_id"]),
        ]


from django.db import models

# Create your models here.
