# Generated by Django 5.2.4 on 2026-03-29 18:57

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0001_initial'),
    ]

    operations = [
        VectorExtension(),
    ]
