# Generated by Django 5.2.4 on 2025-11-07 18:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('protagonist_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The name of the document type (e.g., 'Mémoire de Marie-Josée').", max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'PDF Document Type',
                'verbose_name_plural': 'PDF Document Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the PDF document.', max_length=255)),
                ('file', models.FileField(help_text='The uploaded PDF file.', upload_to='pdf_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('document_date', models.DateField(blank=True, help_text='The date of the document, if applicable.', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the document was uploaded.')),
                ('author', models.ForeignKey(blank=True, help_text='The author of the document, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_pdfs', to='protagonist_manager.protagonist')),
                ('document_type', models.ForeignKey(blank=True, help_text='The type or category of this PDF document.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pdf_manager.pdfdocumenttype')),
            ],
            options={
                'verbose_name': 'PDF Document',
                'verbose_name_plural': 'PDF Documents',
                'ordering': ['-document_date'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_text', models.TextField()),
                ('page_number', models.PositiveIntegerField(help_text='The page number where the quote can be found.')),
                ('quote_location_details', models.CharField(blank=True, help_text="Optional details to locate the quote, e.g., 'Paragraph 3' or 'Header'.", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pdf_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='pdf_manager.pdfdocument')),
            ],
            options={
                'verbose_name': 'PDF Quote',
                'verbose_name_plural': 'PDF Quotes',
                'ordering': ['-created_at'],
            },
        ),
    ]
