# Generated by Django 5.2.4 on 2025-11-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='ai_analysis',
            field=models.TextField(blank=True, help_text="Analyse forensique et résumé généré par l'IA pour économiser les tokens multimodaux.", null=True),
        ),
    ]
