# Generated by Django 5.2.4 on 2025-12-01 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlechat_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ex: Discussion on Sofa Repayment', max_length=255)),
                ('start_timestamp', models.DateTimeField(db_index=True, help_text='Time of the first message in sequence')),
                ('end_timestamp', models.DateTimeField(db_index=True, help_text='Time of the last message')),
                ('messages', models.ManyToManyField(related_name='sequences', to='googlechat_manager.chatmessage')),
                ('subject_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='googlechat_manager.subjectgroup')),
            ],
            options={
                'ordering': ['start_timestamp'],
            },
        ),
    ]
