# Generated by Django 5.2.4 on 2025-12-01 22:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlechat_manager', '0002_chatsequence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatsequence',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='chatsequence',
            name='end_timestamp',
        ),
        migrations.RemoveField(
            model_name='chatsequence',
            name='start_timestamp',
        ),
        migrations.RemoveField(
            model_name='chatsequence',
            name='subject_group',
        ),
        migrations.AddField(
            model_name='chatsequence',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatsequence',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsequence',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatsequence',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
