# Generated by Django 5.2.4 on 2025-11-07 18:27

import django.db.models.deletion
import django.utils.timezone
import photos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('protagonist_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to=photos.models.get_photo_upload_path)),
                ('file_path', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('folder_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('created_on_disk', models.DateTimeField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('image_format', models.CharField(blank=True, max_length=10, null=True)),
                ('image_mode', models.CharField(blank=True, max_length=20, null=True)),
                ('make', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('datetime_original', models.DateTimeField(blank=True, help_text="The naive datetime from the camera's EXIF data.", null=True)),
                ('datetime_utc', models.DateTimeField(blank=True, help_text='The timezone-aware UTC datetime, typically from an XMP sidecar file.', null=True)),
                ('iso_speed', models.IntegerField(blank=True, null=True)),
                ('artist', models.CharField(blank=True, max_length=255, null=True)),
                ('exposure_time', models.CharField(blank=True, max_length=50, null=True)),
                ('f_number', models.FloatField(blank=True, null=True)),
                ('focal_length', models.FloatField(blank=True, null=True)),
                ('lens_model', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_width', models.IntegerField(blank=True, null=True)),
                ('raw_height', models.IntegerField(blank=True, null=True)),
                ('color_depth', models.IntegerField(blank=True, null=True)),
                ('num_colors', models.IntegerField(blank=True, null=True)),
                ('cfa_pattern', models.CharField(blank=True, max_length=50, null=True)),
                ('gps_latitude', models.FloatField(blank=True, null=True)),
                ('gps_longitude', models.FloatField(blank=True, null=True)),
                ('gps_altitude', models.FloatField(blank=True, null=True)),
                ('gps_timestamp', models.DateTimeField(blank=True, null=True)),
                ('all_metadata_json', models.JSONField(blank=True, default=dict, null=True)),
                ('date_folder', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['datetime_original'],
            },
        ),
        migrations.CreateModel(
            name='PhotoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='A descriptive title for the document.', max_length=255)),
                ('description', models.TextField(blank=True, help_text="Optional notes or a summary of the document's content.")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time the document was created.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, help_text='The author of the document, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_photo_documents', to='protagonist_manager.protagonist')),
                ('photos', models.ManyToManyField(help_text='The photos that make up this document.', related_name='photo_documents', to='photos.photo')),
            ],
            options={
                'verbose_name': 'Photo Document',
                'verbose_name_plural': 'Photo Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photos.phototype'),
        ),
    ]
