# Generated by Django 5.2.4 on 2025-11-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photodocument',
            name='ai_analysis',
            field=models.TextField(blank=True, help_text="Description détaillée du contenu visuel générée par l'IA.", null=True),
        ),
    ]
