# Generated by Django 5.2.4 on 2026-03-30 12:29

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photodocument_ai_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='photodocument',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
