# Generated by Django 5.2.4 on 2025-11-07 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('protagonist_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(db_index=True, help_text='The unique ID for the email thread (e.g., from Gmail).', max_length=255, unique=True)),
                ('subject', models.CharField(blank=True, help_text='The subject of the conversation, typically from the first email.', max_length=500, null=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('protagonist', models.ForeignKey(blank=True, help_text='The protagonist associated with this email thread.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_threads', to='protagonist_manager.protagonist')),
            ],
            options={
                'verbose_name': 'Email Thread',
                'verbose_name_plural': 'Email Threads',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('dao_source', models.CharField(help_text='The source used to acquire this email (e.g., Gmail).', max_length=50)),
                ('subject', models.CharField(blank=True, max_length=500, null=True)),
                ('sender', models.CharField(blank=True, max_length=255, null=True)),
                ('recipients_to', models.TextField(blank=True, help_text="Comma-separated 'To' recipients", null=True)),
                ('recipients_cc', models.TextField(blank=True, help_text="Comma-separated 'Cc' recipients", null=True)),
                ('recipients_bcc', models.TextField(blank=True, help_text="Comma-separated 'Bcc' recipients", null=True)),
                ('date_sent', models.DateTimeField(blank=True, null=True)),
                ('body_plain_text', models.TextField(blank=True, null=True)),
                ('eml_file_path', models.CharField(max_length=1024)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('recipient_protagonists', models.ManyToManyField(blank=True, help_text='The protagonists who received this email.', related_name='received_emails', to='protagonist_manager.protagonist')),
                ('sender_protagonist', models.ForeignKey(blank=True, help_text='The protagonist who sent this email.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to='protagonist_manager.protagonist')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='email_manager.emailthread')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
                'ordering': ['date_sent'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='email_manager.email')),
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quotes',
                'ordering': ['-created_at'],
            },
        ),
    ]
