# Generated by Django 5.2.4 on 2025-12-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='eml_file',
            field=models.FileField(blank=True, null=True, upload_to='emails/'),
        ),
    ]
